name: pnpm
description: 'Setup node & pnpm'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
    - name: Install npm package dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    - name: Build all dependencies
      run: pnpm nx build
