name: pnpm
description: 'Setup node & pnpm'

runs:
  using: 'composite'
  steps:
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install npm package dependencies
        run: pnpm install --frozen-lockfile
