name: cli
on:
  push:
    branches:
      - main
    paths:
      - 'packages/cli/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/cli.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/cli/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/cli.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: pnpm/action-setup@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @storacha/cli run lint
      - run: pnpm -r --filter @storacha/cli run check
      - run: pnpm -r --filter @storacha/cli run test
