name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{steps.release.outputs.paths_released}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          command: manifest
  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test
      - run: npm publish --workspace ${{steps.release.outputs.paths_released}} --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
